# Generated by Django 5.0.6 on 2024-07-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_entry.category')),
            ],
        ),
    ]
